### ISSUE TITLE
After pfelk update, logstash complains about grok

### ISSUE THREAD

**Issue by klausagnoletti** [pfelk/pfelk#262]
**Describe the bug**
I updated pfelk for the first time since november. After updating pipelines (and fineadjusting paths and other settings) Logstash complains:
[ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{PF_APP} not defined>, 

I am aware that I am not providing much information since I couldn't see the relevance for most of what you ask in my case. Let me know what you need to help me out. 

**To Reproduce**
Hard to reproduce. I did customizations on the original install since I am running everything in my own Docker setup of three separate containers (each with its own component in the stack). So copying the new pipeline files in is a manual process, copying each file one at a time and correcting errors as I go.

**Screenshots**
N/A

**Firewall System (please complete the following information):**
OPNsense 21.1
 
**Operating System (please complete the following information):**
 - OS 
Linux 4.19.0-14-amd64 x86_64
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 
 **Installation method (manual, ansible-playbook, docker, script):**
Custom docker setup 

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
Newest version of everything (7.10.2).
 
 **Elasticsearch, Logstash, Kibana logs:**
Let me know if you need more logs

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by a3ilson** [comment]
@klausagnoletti -

Thanks for the inquire and your contribution to improve this project!

After reviewing the related lines associated to PF_APP, it was noted that the patterns were not delineated which likely resulted in your error(s).  Please update your [05-apps.conf](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/05-apps.conf) file, restart logstash and confirm this fixed/corrected your issue/error.


Explanation: 
File [05-apps.conf](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/05-apps.conf), line 118 specifies to match the filter_message against the ```"%{PF_APP}", "%{PF_APP_DATA}"``` with the reference GROK pattern located at ```"/etc/logstash/conf.d/patterns"``` 

The [pfelk.grok](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/patterns/pfelk.grok) file matches the filter_message (line 70-75)

The issues was that within the [05-apps.conf](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/05-apps.conf) file, on line 118, the referenced GROK pattern was ```"%{PF_APP}%{PF_APP_DATA}"``` and the two were essentially one.  This was corrected and now both GROK patterns are defined (e.g. ```"%{PF_APP}", "%{PF_APP_DATA}"```)

**Comment by klausagnoletti** [comment]
Thanks for creating and maintaining the project - and to actively work on compatability with ECS going forward :-)

As it turns out there were two problems. First of all the docker image of logstash expects all configs in `/usr/share/logstash/config`. I have been updating that in each other file in the pipeline config but missed this. I changed it and did as you suggested. Now I get another error from logstash:

```
[2021-02-06T16:28:21,975][INFO ][logstash.javapipeline    ][.monitoring-logstash] Pipeline started {"pipeline.id"=>".monitoring-logstash"}
[2021-02-06T16:28:25,102][ERROR][logstash.filters.grok    ] Invalid setting for grok filter plugin:
  filter {
    grok {
      # This setting must be a hash
      # This field must contain an even number of items, got 3

      match => ["filter_message", "%{PF_APP}", "%{PF_APP_DATA}"]
```
I know absolutely nothing about grok so I hope you can fix it :)

For the record I've updated my `docker-compose.yml` with a bind mount that maps `/usr/share/logstash/config` to `/etc/logstash/conf.d` to make future updates easier - basically it accepts config files at both paths :)

Thanks

/klaus

**Comment by a3ilson** [comment]
Give it another try - I updated the file which amends line 118 to the following : `match => { "filter_message" => [ "%{PF_APP}", "%{PF_APP_DATA}" ] }`

If that doesn't work, I'll update the grok pattern to get it working.  I do not receive these logs so, apologizes for being unable to test but thank you for validating!

Quick question regarding your setup. There were previous efforts to get this project compatible with UNRAID but it required a true docker vs docker compose. Is your setup reliant on docker compose and/or did you get it running with docker?

**Comment by klausagnoletti** [comment]
Unfortunately it's still pissed. Now it's the definition of another field:
`[ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{DHCPD} not defined>, `

I am running my setup on a Debian host based on a modified version of https://github.com/sherifabdlnaby/elastdocker. I modified it to use SSL in the entire stack, to include different beats but the basic idea to run everything using docker-compose and each element in it's own docker container is the same. I find that a more elegant approach than the all-in-one approach used in the container you provide :) (also, I already had that running).

It's going to take a bit of work to prepare but if you want my version of the elastdocker setup I have made, let me know.

Thanks

/k

**Comment by a3ilson** [comment]
That one was interesting...mine was working without issue but looking over the GROK pattern, I noted a few issues - corrected. What are you running OPNsense or pfSense and version?

Please update to the latest [pfelk.grok](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/patterns/pfelk.grok) file and try again...


I would be interested in your Docker yaml's...at your leisure feel free to email (andrew@pfelk.com)

**Comment by klausagnoletti** [comment]
Yuck, same error.

I am running latest version of OPNsense - 12.1.

I'll send you my docker-compose.yaml shortly.

Thanks

/k

**Comment by a3ilson** [comment]
Did the GROK pattern update fix your latest error?

**Comment by klausagnoletti** [comment]
No, I got the exact same error

`[ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{DHCPD} not defined>`

Sorry if that wasn't clear enough.

**Comment by a3ilson** [comment]
No worries...

For this particular error (DHCP), I would suggest looking over your conf file.  The 05-apps.conf has multiple grok pattern references. The DHCP starts on line 29, with line 36 specifying the GROK file path - since your running within a docker, I would confirm this path is correct (i.e. points/references the pfelk.grok file).

**Comment by klausagnoletti** [comment]
Thanks. That's it, it seems. My mounts needs to be fixed - the error has changed now:

`ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{PF_LOG_ENTRY} not defined>`

Do you know if it's possible to put in a relative path in the conf files going forward? That would be an elegant way to fix it so it would work in both environments, I think.

In the meantime I will update the rest of the path entries in the file.

/k

**Comment by klausagnoletti** [comment]
Argh. Only absolute paths :-(

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-path

Would it be possible to define a base dir for configuration files in an external file that's set as a variable of sorts and the imported to the conf file during runtime, maybe?

/k

**Comment by a3ilson** [comment]
Gotcha - You'll need to change all those referenced paths.  The [Docker](https://github.com/pfelk/docker) variant already has a revised path but I need to update that repo which is on my list of things to do.  

Two thoughts:
- I could add to the script installer 
  - set to default 
  - set to user defined path
- I could add multiple paths which would check both for the referenced file(s)


Since all the paths are the same you could leverage sed to replace all instances with the desired path.

**Comment by a3ilson** [comment]
Here's an example of leveraging sed to change all instances:

```sed -i 's#/usr/share/logstash/etc/logstash/conf.d/patterns#/enter/your/path/here#g' 05-apps.conf```

**Comment by klausagnoletti** [comment]
Gotcha on the sed thing - I already looked it up :)

Thanks for the suggestions. One weakness of putting it in the installer is that it may take away flexibility. In my case I have obviously not used scripts. So in that case the latter possibility of multiple paths would be good; after all that is the path used in Elastic's official docker image. 

I now get a bunch of warnings in the Logstash log:

`[WARN ][logstash.filters.grok    ][main][28063f9fb078d712ba01e4def752ca35b1a92dc669a7f520386e96fb2c20a116] Grok regexp threw exception {:exception=>"Could not set field 'hostname' on object '10.20.30.1' to value 'switch'.This is probably due to trying to set a field like [foo][bar] = someValuewhen [foo] is not either a map or a string", `

Do you have any idea how to fix that? 10.20.30.1 is one of my firewalls. I guess I need to set the hostname somewhere.

But now at least Logstash manages to keep running. Which is a great improvement I must say :-)

Thanks!

/k

**Comment by a3ilson** [comment]
I'd have to review your conf files for that particular error...all `hostname` fields are nested, to conform with ECS.

I'd check your configuration files (e.g. `grep hostname *.conf`) there should only be a few instances:
- 03-filter.conf - nested under observer
- 05-apps.conf - nested under host
- pfelk.grok - all nested under host and all related to dhcp

**Comment by a3ilson** [comment]
@klausagnoletti - After reevaluating this thread I wanted to propose an alternative.

(1) Continue to troubleshoot 
or
(2) Now might be a great time to revise the [pfelk/docker](https://github.com/pfelk/docker) repo which relies on Docker Compose.  Updating to work with Docker will also enable an easy transmission for Kubernetes. 

I am currently awaiting a replacement motherboard and will resume and explore this solution this coming weekend.  Ideally, I'll have a working pfelk docker for Elasticsearch, Kibana and Logstash which ought to mitigate this issue.

References:
https://www.elastic.co/guide/en/logstash/current/docker-config.html
https://www.elastic.co/guide/en/kibana/current/docker.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by klausagnoletti** [comment]
Good that you propose an alternative because I was a bit confused regarding those three files since I haven't done any editing in them and there are no obvious things to do with them in terms of adapting to my setup.

However, looking through the Logstash logfiles again confused me even more. 
There seems to be a few very long entires starting with something like this:
```
Could not set field 'hostname' on object '10.20.30.1' to value 'sniffer'
Could not set field 'hostname' on object '10.20.30.1' to value 'switch'
Could not set field 'hostname' on object '10.20.30.1' to value 'flaplet'
Could not set field 'hostname' on object '10.20.30.1' to value 'AP1'
Could not set field 'hostname' on object '10.20.30.1' to value 'Chromecast'
```

There are more. These are just examples. The things that varies are existing hostnames on my network (and the ip is not that. 10.20.30.1 is one of my firewalls. All but one of those hosts above are assigned by DHCP and fed into unbound as DNS records. I also have a pi-hole. Not sure where this fits in. Anyway, could this be an error originating from a missing PTR record (or just not being able to do a PTR lookup) of whatever ip is assigned to, say, sniffer?

Also, regarding your other suggestion regading updating your docker setup, I am not sure where this leaves my setup. I need convincing to change my current setup - but I will be happy to help you out in any way I can. 

On a different note I do have some Kibana dashboards not working completely, some data here and there seem to be missing. Not sure if this could have anything to do with me updating current dashboards and templates (and choosing to overwrite existing data. I guess troubleshooting this should be a different thread :)

Let me know if we should set up a separate channel for communication and collaboration going forward if you need my help. This doesn't seem to be the best fit :)

/k

**Comment by a3ilson** [comment]
@klausagnoletti - I sent you a message requesting specifics to better troubleshoot/isolate and correct the issue.

**Comment by a3ilson** [comment]
Built a similar setup utilizing the repo files from pfelk and the docker-compose.yml file below.  Everything worked and has been running for two days.


```
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
      
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.0
    container_name: logstash
    environment:
      LS_JAVA_OPTS: -Xms8G -Xmx8G
    volumes:
      - /etc/pfelk/config:/usr/share/logstash/config:ro
      - /etc/pfelk/conf.d:/usr/share/pfelk/conf.d:ro
      - /etc/pfelk/patterns:/usr/share/pfelk/patterns:ro
      - /etc/pfelk/databases:/usr/share/pfelk/databases:ro
    ports:
      - 5140:5140/udp
      - 5040:5040 
      - 9600:9600
    networks:
      - elastic
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
```

Here is my file tree on the host system:
```
/etc/pfelk/
── conf.d
│   ├── 01-inputs.conf
│   ├── 02-types.conf
│   ├── 03-filter.conf
│   ├── 05-apps.conf
│   ├── 20-interfaces.conf
│   ├── 30-geoip.conf
│   ├── 35-rules-desc.conf
│   ├── 36-ports-desc.conf
│   ├── 45-cleanup.conf
│   └── 50-outputs.conf
── config
│   ├── logstash.yml
│   └── pipelines.yml
── databases
│   ├── rule-names.csv
│   └── service-names-port-numbers.csv
── logs
── patterns
    └── pfelk.grok
```

Required adjustments:
- amended line 15 in 35-rules-desc.conf to: `dictionary_path => "/usr/share/pfelk/databases/rule-names.csv"`
- amended lines 15/25 in 36-ports-desc.conf to: `dictionary_path => "/usr/share/pfelk/databases/service-names-port-numbers.csv"`

The source path (docker-compose.yml) may be anywhere you desire but I utilized the default (/usr/share/pfelk & /usr/share/logstash) paths, to keep it simple.

logstash.yml
```
http.host: "0.0.0.0"
#path.config: /usr/share/logstash/pipeline/pipelines.yml
xpack.monitoring.elasticsearch.hosts: [ "http://es01:9200" ]

## X-Pack security credentials
xpack.monitoring.enabled: true
```


pipelines.yml
```
# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: pfelk
```
